### PR TITLE
docs: remove terraformrc setup

### PR DESCRIPTION
**Pull request by zbwright**

### CODE REVIEW

**Comment by zbwright** [comment]
I'm not clear on what this change means. Users no longer define a build directory? Drop the entire *Create a cluster build directory* section? If so, do they still edit the `terraform.tfvars` file? and what does `tectonic_cluster_name` become?

**Comment by alexsomesan** [comment]
Sorry, @zbwright I might have rushed this proposal to remove it.
I noticed now that we have some command examples further down that reference it. They are more convenient to copy-paste verbatim if we keep the instructions to export CLUSTER.
Sorry for causing confusion. Let's keep it in there.

One more thought - in this document we should have a new paragraph before the "Deploy the cluster" one where we document the need to run `terraform init`. I'd call it something like "Initialize Terraform" and the command example should look like the one we had for `get` but with `init` instead of `get`.

**Comment by zbwright** [comment]
@alexsomesan no problem at all.

**Comment by zbwright** [comment]
@alexsomesan one more "approve" and we can merge. are we good now?

**Pull request merged**
