### PR TITLE
docs: add missing permission

### PR DESCRIPTION
**Pull request by cpanato**
fixes: https://github.com/coreos/bugs/issues/2266 and INST-714

### CODE REVIEW

**Comment by sym3tri** [comment]
@cpanato LGTM
But can you link to the PR that introduced the change?

**Comment by cpanato** [comment]
This PR introduce the changes: https://github.com/coreos/tectonic-installer/pull/2362

cc @sym3tri

**Comment by sym3tri** [comment]
@cpanato are you sure? I don't see `ListRoles` in the diff.

**Comment by cpanato** [comment]
@sym3tri  sorry it came from here: https://github.com/coreos/bugs/issues/2266

**Comment by sym3tri** [comment]
@cpanato that's just the request to add it. Is there someplace recently that added that permission as a requirement?

Maybe @s-urbaniak knows?

**Comment by s-urbaniak** [comment]
Code blocks like this
https://github.com/coreos/tectonic-installer/blob/master/modules/aws/master-asg/master.tf#L92-L95
could be the source. But after looking at the TF code this invokes
iam:GetRole. Maybe the OP hits edge cases enumerated here:
https://www.terraform.io/docs/providers/aws/index.html#getting-the-account-id
.

**Comment by sym3tri** [comment]
Figured it out with Carlos. It was an addition to the GUI backend.

**Pull request merged**
